const certificates = [
  // Medical & health
  {id:'undip-medicine', title:'Summer Course on Health Resilience in Disaster: Community and Clinical Responses to Climate Risks', issuer:'Faculty of Medicine, Universitas Diponegoro', date:'3–13 August 2026', category:'medical', image:'assets/certificates/medical/undip-fom-summer-course.jpg', meta:'48 learning hours • 3 academic credits • 4.5 ECTS • Certificate No. 256/UN7.F4/LL/VIII/2026', description:'Successfully participated in the Faculty of Medicine summer course on health resilience in disaster, with community and clinical responses to climate risks.', featured:true},
  {id:'stanford-hypertension', title:'Hypertension in Primary Care: Improving Control and Reducing Risk', issuer:'Stanford Medicine', date:'2026', category:'medical', image:'assets/certificates/medical/stanford-hypertension.jpg', description:'Medical learning focused on hypertension in primary care and risk reduction.'},
  {id:'who-hearts', title:'Training on HEARTS technical package for clinicians', issuer:'World Health Organization', date:'20 January 2026', category:'medical', image:'assets/certificates/medical/who-hearts-clinicians.jpg', description:'Completed WHO online training on the HEARTS technical package for clinicians.'},
  {id:'longevity', title:'Longevity Medicine', issuer:'HDR UK', date:'2026', category:'medical', image:'assets/certificates/medical/longevity-medicine.jpg', description:'Completed professional learning in longevity medicine.'},
  {id:'first-aid', title:'First Aid & Emergency Response', issuer:'The Muslim School & College, Gujrat', date:'2026', category:'medical', image:'assets/certificates/medical/first-aid-emergency-response.jpg', description:'Participation certificate for learning in first aid and emergency response.'},
  {id:'metals', title:'Metals in medicine', issuer:'OpenLearn • The Open University', date:'19 January 2026', category:'medical', image:'assets/certificates/medical/openlearn-metals-in-medicine.jpg', description:'OpenLearn statement of participation for the course Metals in medicine.'},
  {id:'microbes', title:'Microbes – friend or foe?', issuer:'OpenLearn • The Open University', date:'4 January 2026', category:'medical', image:'assets/certificates/medical/openlearn-microbes.jpg', description:'OpenLearn course exploring microbes and their role in health and disease.'},
  {id:'infectious-disease', title:'Public health approaches to infectious disease', issuer:'OpenLearn • The Open University', date:'7 February 2026', category:'medical', image:'assets/certificates/medical/openlearn-public-health-infectious-disease.jpg', description:'OpenLearn learning on infectious disease from a public-health perspective.'},
  {id:'public-health', title:'Introducing public health', issuer:'OpenLearn • The Open University', date:'30 January 2026', category:'medical', image:'assets/certificates/medical/openlearn-introducing-public-health.jpg', description:'OpenLearn statement of participation introducing key public-health ideas.'},
  {id:'hearts-sport', title:'Exploring sport online: Athletes and efficient hearts', issuer:'OpenLearn • The Open University', date:'19 January 2026', category:'medical', image:'assets/certificates/medical/openlearn-athletes-efficient-hearts.jpg', description:'OpenLearn learning on the heart, circulation, lungs and athletic performance.'},
  {id:'unicef-health-economics', title:'Health Economics and Financing', issuer:'UNICEF via Agora', date:'13 January 2026', category:'medical', image:'assets/certificates/medical/unicef-health-economics.jpg', description:'Completed a UNICEF learning course on health economics and financing.'},

  // International
  {id:'vip', title:'2026 Vocational International Program (VIP) Summer Course', issuer:'Universitas Diponegoro', date:'19–20 August 2026', category:'international', image:'assets/certificates/international/vip-summer-course.jpg', meta:'Digital Brandscapes: The Strategic Impact of Communication on Global Tourism • No. 018/UN7.M2/HK/IX/2026', description:'International learning in digital communication, sustainable tourism, environmental advocacy, social media campaigns and tourism branding.'},
  {id:'global-youth', title:'2026 Global Youth Conference: Radical Compassion in Action for Justice', issuer:'Charter for Compassion', date:'23–24 September 2026', category:'international', image:'assets/certificates/international/global-youth-conference.jpg', meta:'Virtual conference • Certificate of Attendance', description:'Participated in the global youth conference focused on compassion, justice and meaningful action.'},
  {id:'studying-medicine', title:'Studying medicine globally', issuer:'OpenLearn • The Open University', date:'4 January 2026', category:'international', image:'assets/certificates/international/openlearn-studying-medicine-globally.jpg', description:'OpenLearn statement of participation focused on studying medicine globally.'},
  {id:'adbi-circular', title:'ADBI Policy Maker E-Training: Circular Economy', issuer:'Asian Development Bank Institute', date:'22 January 2026', category:'international', image:'assets/certificates/international/adbi-circular-economy.jpg', description:'Completed an ADBI e-training course on circular economy concepts.'},

  // Leadership & impact
  {id:'csr', title:'Leaders of Social Impact Program — Cohort 10.0', issuer:'CSR Forum Pakistan', date:'1 April – 2 May 2026', category:'leadership', image:'assets/certificates/leadership/csr-leaders-social-impact.jpg', meta:'Certificate of Completion • issued 5 May 2026', description:'Successfully completed the Leaders of Social Impact Program, Cohort 10.0, with a focus on leadership, social impact and community-oriented action.'},
  {id:'unicef-accessibility', title:'Design with Inclusion in Mind: Digital Accessibility Fundamentals', issuer:'UNICEF via Agora', date:'17 March 2026', category:'leadership', image:'assets/certificates/leadership/unicef-digital-accessibility.jpg', meta:'Certificate ID J9XNV1NvEo', description:'Completed UNICEF learning on digital accessibility and inclusion.'},

  // Digital skills
  {id:'ai-ready', title:'AI Ready Pakistan – AI Foundations Programme, Cohort I', issuer:'AI Ready Pakistan', date:'9 August – 13 September 2026', category:'digital', image:'assets/certificates/digital/ai-ready-pakistan.jpg', meta:'Certificate ID ARP-COCI-S023 • 11 structured learning sessions', description:'Completed foundational and practical AI learning covering AI fundamentals, video, graphics, coding, productivity, prompt engineering, marketing, responsible AI, research and academic writing.'},
  {id:'digiskills-video', title:'Video Editing, Animation and Vlogging', issuer:'DigiSkills.pk / Ignite / Virtual University', date:'20 July 2026', category:'digital', image:'assets/certificates/digital/digiskills-video-editing.jpg', meta:'DSTP3.0-Batch-03 Apr 2026–Jul 2026 • Certificate ID PG2YZAVMK', description:'Completed DigiSkills training in video editing, animation and vlogging.'},
  {id:'digiskills-freelance', title:'Freelancing', issuer:'DigiSkills.pk / Ignite / Virtual University', date:'20 July 2026', category:'digital', image:'assets/certificates/digital/digiskills-freelancing.jpg', meta:'DSTP3.0-Batch-03 Apr 2026–Jul 2026 • Certificate ID U5NTC6JMK', description:'Completed DigiSkills training in freelancing.'},
  {id:'ai-storytelling', title:'AI-powered content, storytelling & advocacy', issuer:'PoliSync • Globethics • Initiatives of Change • ICVA • Microsoft Elevate', date:'6 May 2026', category:'digital', image:'assets/certificates/digital/ai-content-storytelling.jpg', meta:'Serial No. cert_c94qqrs1', description:'Completed online learning on AI-powered content, storytelling and advocacy.'},
  {id:'ai-governance', title:'AI foundations: ethics, governance & prompting', issuer:'PoliSync / partner learning initiative', date:'2026', category:'digital', image:'assets/certificates/digital/ai-content-governance-prompting.jpg', description:'Completed learning focused on AI foundations, ethics, governance and prompting.'},
  {id:'cybersecurity', title:'Cybersecurity in the Era of Digitalization', issuer:'Global Engineering Network for Innovation and Intelligence (GEN_II)', date:'28 July 2026', category:'digital', image:'assets/certificates/digital/gen-ii-cybersecurity.jpg', meta:'2-day training workshop', description:'Certificate of completion for a two-day cybersecurity workshop.'},

  // Communication, conferences, awards
  {id:'ieee', title:'Power User on Locating Technical Resources: An in-depth dive with IEEE Xplore Digital Library', issuer:'IEEE', date:'24 July 2026', category:'communication', image:'assets/certificates/communication/ieee-xplore-attendance.jpg', meta:'Certificate of Attendance', description:'Participated in a technical resources session focused on IEEE Xplore.'},
  {id:'speech-award', title:'Speech Competition Achievement Certificate', issuer:'The Urban School, Gujrat', date:'14 August 2025', category:'communication', image:'assets/certificates/communication/urban-speech-competition.jpg', meta:'First Position • Independence Day • theme: History and Culture', description:'Secured first position in the Speech Competition held on Independence Day at The Urban School, Gujrat.'},
  {id:'science-award', title:'Science Competition Achievement Certificate', issuer:'The Urban School, Gujrat', date:'18 October 2025', category:'communication', image:'assets/certificates/communication/urban-science-competition.jpg', meta:'Second Position • competition among science educators', description:'Secured second position in the Science Competition organized by The Urban School, Gujrat.'},
  {id:'iscops', title:'International Student Conference on Public Speaking (ISCOPS) 2026 — Certificate of Recognition', issuer:'UKM English Debating Society, Politeknik Negeri Sriwijaya', date:'26 September 2026', category:'communication', image:'assets/certificates/communication/iscops-2026.jpg', meta:'Certificate ID 135/S.EDS/IX/2026 • Participant', description:'Recognized as a participant in ISCOPS 2026, organized by the English Debating Society of Politeknik Negeri Sriwijaya.'},
  {id:'ymn', title:'Article Writing Competition — 2nd Position', issuer:'Youth Media Network Pakistan', date:'8 September 2026', category:'communication', image:'assets/certificates/communication/ymn-article-writing.jpg', meta:'International Literacy Day • Certificate of Recognition', description:'Secured 2nd position in the Article Writing Competition organized by YMN Pakistan on International Literacy Day.'},
  {id:'world-youth-skills', title:'World Youth Skills Day', issuer:'Youth / SDG partner webinar', date:'15 July 2026', category:'communication', image:'assets/certificates/communication/world-youth-skills-day.jpg', meta:'Certificate of Participation • webinar', description:'Successfully attended a webinar connected to World Youth Skills Day.'},
  {id:'world-population-day', title:'World Population Day', issuer:'Youth / SDG partner webinar', date:'11 July 2026', category:'communication', image:'assets/certificates/communication/world-population-day.jpg', meta:'Certificate of Participation', description:'Participated in a learning and awareness webinar connected to World Population Day.'},

  // Volunteering / service
  {id:'alkhidmat-award', title:'Alkhidmat Summer Internship Program 2026 — Achievement Award', issuer:'Alkhidmat Foundation Pakistan', date:'2026', category:'volunteering', image:'assets/certificates/volunteering/alkhidmat-achievement-award.jpg', meta:'Volunteer Management Department • Certificate of completion / achievement', description:'Official internship achievement certificate from Alkhidmat Foundation Pakistan.'},
  {id:'vfp-teams', title:'Language of High-Performing Teams', issuer:'Volunteer Force Pakistan', date:'2026', category:'volunteering', image:'assets/certificates/volunteering/vfp-high-performing-teams.jpg', meta:'Certificate of Participation • online session', description:'Participated in a Volunteer Force Pakistan learning session on communication and collaboration in high-performing teams.'}
];

const projects = [
  {title:'Sleep Smart Youth Initiative', tag:'HEALTH & YOUTH', image:'assets/projects/sleep-smart.jpg', description:'A youth-oriented project exploring sleep health, academic performance, awareness, inclusion and practical action.', evidence:'assets/projects/sleep-smart-evidence.jpg'},
  {title:'Gen Z Entrepreneurship Initiative', tag:'ENTREPRENEURSHIP', image:'assets/projects/gen-z.jpg', description:'A community-oriented entrepreneurship project involving survey work, startup ideas, social-media awareness and evaluation.', evidence:'assets/projects/gen-z-evidence.jpg'},
  {title:'Young Minds, Big Dreams', tag:'YOUTH OUTREACH', image:'assets/projects/young-minds.jpg', description:'A communication and awareness project using design, messaging and youth-focused storytelling.', evidence:'assets/projects/young-minds-evidence.jpg'},
  {title:'Alkhidmat Internship Documentation', tag:'REPORTING & IMPACT', image:'assets/projects/alkhidmat-report.jpg', description:'Selected internship reports, assignments and documentation showing planning, implementation, reflection and impact reporting.', evidence:'assets/projects/alkhidmat-report.jpg'}
];

const activities = [
  {type:'internships', icon:'🤝', title:'Alkhidmat Summer Internship Program', subtitle:'Volunteer Management Department', date:'30 June – 30 August 2026', description:'Humanitarian learning, emergency preparedness, community action, digital skills, volunteer mobilization, reporting and project work.'},
  {type:'internships', icon:'🌱', title:'Leaders of Social Impact — Cohort 10.0', subtitle:'CSR Forum Pakistan', date:'1 April – 2 May 2026', description:'Structured learning around leadership, social impact, collaboration, community engagement and practical impact thinking.'},
  {type:'volunteering', icon:'🌍', title:'Friends of the Corner Volunteer', subtitle:'Lincoln Corners Peshawar', date:'Sep 2026 – Feb 2027', description:'Youth-focused community participation spanning creative writing, STEM, events and program support.'},
  {type:'volunteering', icon:'🧼', title:'Health & Hygiene Campaign', subtitle:'Community service', date:'1 November 2025', description:'Participated in a health and hygiene awareness activity focused on community wellbeing.'},
  {type:'volunteering', icon:'🧹', title:'Cleanliness Activity', subtitle:'Community service', date:'6 December 2025', description:'Participated in a community cleanliness initiative.'},
  {type:'volunteering', icon:'🩹', title:'Health Club & First Aid / Emergency Response', subtitle:'Student service & learning', date:'2025–2026', description:'Health-focused activities supporting awareness, basic emergency response and peer learning.'},
  {type:'conferences', icon:'🌎', title:'2026 Global Youth Conference', subtitle:'Charter for Compassion', date:'23–24 September 2026', description:'Virtual global youth learning on compassion, justice and meaningful action.', certId:'global-youth'},
  {type:'conferences', icon:'🎤', title:'ISCOPS 2026', subtitle:'English Debating Society, Politeknik Negeri Sriwijaya', date:'26 September 2026', description:'International student conference on public speaking, communication and confidence.', certId:'iscops'},
  {type:'webinars', icon:'💬', title:'Language of High-Performing Teams', subtitle:'Volunteer Force Pakistan', date:'2026', description:'Session on effective communication, collaboration and team practices.', certId:'vfp-teams'},
  {type:'webinars', icon:'🧠', title:'World Youth Skills Day', subtitle:'Youth / SDG partner webinar', date:'15 July 2026', description:'Participated in a webinar linked to skills development and youth learning.', certId:'world-youth-skills'},
  {type:'webinars', icon:'👥', title:'World Population Day', subtitle:'Youth / SDG partner webinar', date:'11 July 2026', description:'Participated in a learning and awareness webinar.', certId:'world-population-day'}
];
